dist: focal
sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_168e876d7368_key -iv $encrypted_168e876d7368_iv -in multi-k8s-457516-138f96d4b015.json.enc -out ./multi-k8s-457516-138f96d4b015.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file multi-k8s-457516-138f96d4b015.json
  - gcloud config set project 	multi-k8s-457516
  - gcloud config set compute/zone us-central1-a
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t bdimmler/react-test -f ./client/Dockerfile.dev ./client
script:
    -docker run -e CI=true bdimmler/react-test npm test
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
   branch: master